version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - /Users/ijisu/Desktop/postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"

networks:
  default:
    driver: bridge
